name: Deploy website
on:
  push:
    branches:
      - Dev
jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.test-output.outputs.message }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Set Output
      id: test-output
        run: echo 'message[]' >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
